language: node_js

node_js:
  - lts/*

script:
  - npx urlint && curl -sL https://hc-ping.com/79188d8c-eec1-447a-b38e-3180b559e3c4

stages:
  - Test
  - name: Release
    if: commit_message !~ /(release|no-release)/


jobs:
  include:
    - stage: Release
      node_js: lts/*
      install: npm install --no-package-lock
      before_deploy:
        - git config user.email ${GITHUB_EMAIL:-"travis@travis-ci.org"}
        - git config user.name ${GITHUB_USER:-"Travis CI"}
        - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
      deploy:
        skip_cleanup: true
        provider: script
        script: npm run release
        on:
          branch: master
