title: frankie
email: frankiebeatriceiii@gmail.com
description: A millennial doing stuff on internet that ships software every day and builds digital products.
github: FrankBeatrice
author: FrankBeatrice
logo: /images/avatar-glitch.jpg

social:
  name: FrankBeatrice
  links:
    - https://twitter.com/beatricefrankie
    - https://github.com/frankbeatrice
    - https://www.linkedin.com/in/frankbeatrice

twitter:
  username: beatricefrankie

permalink: "/:title/"
disqus_shortname: 
google_analytics: 

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

plugins:
  - jekyll-archives
  - jekyll-autoprefixer
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories
